import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ['Nunito', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        subject: {
          math: "hsl(var(--subject-math))",
          english: "hsl(var(--subject-english))",
          kiswahili: "hsl(var(--subject-kiswahili))",
          science: "hsl(var(--subject-science))",
          social: "hsl(var(--subject-social))",
          cre: "hsl(var(--subject-cre))",
          phy: "hsl(var(--subject-phy))",
          chem: "hsl(var(--subject-chem))",
          bio: "hsl(var(--subject-bio))",
          hist: "hsl(var(--subject-hist))",
          geo: "hsl(var(--subject-geo))",
          business: "hsl(var(--subject-business))",
          agriculture: "hsl(var(--subject-agriculture))",
          default: "hsl(var(--subject-default))",
          break: "hsl(var(--subject-break))",
          games: "hsl(var(--subject-games))",
          ire: "hsl(var(--subject-ire))",
          hre: "hsl(var(--subject-hre))",
          ict: "hsl(var(--subject-ict))",
          french: "hsl(var(--subject-french))",
          german: "hsl(var(--subject-german))",
          arabic: "hsl(var(--subject-arabic))",
          mandarin: "hsl(var(--subject-mandarin))",
          music: "hsl(var(--subject-music))",
          art: "hsl(var(--subject-art))",
          "home-science": "hsl(var(--subject-home-science))",
          computer: "hsl(var(--subject-computer))",
          "life-skills": "hsl(var(--subject-life-skills))",
          health: "hsl(var(--subject-health))",
          "pre-tech": "hsl(var(--subject-pre-tech))",
          community: "hsl(var(--subject-community))",
          ksl: "hsl(var(--subject-ksl))",
          indigenous: "hsl(var(--subject-indigenous))",
          "math-activities": "hsl(var(--subject-math-activities))",
          "env-activities": "hsl(var(--subject-env-activities))",
          hygiene: "hsl(var(--subject-hygiene))",
          movement: "hsl(var(--subject-movement))",
          "sci-tech": "hsl(var(--subject-sci-tech))",
          "creative-arts": "hsl(var(--subject-creative-arts))",
          phe: "hsl(var(--subject-phe))",
          "pure-math": "hsl(var(--subject-pure-math))",
          "applied-math": "hsl(var(--subject-applied-math))",
          statistics: "hsl(var(--subject-statistics))",
          "env-science": "hsl(var(--subject-env-science))",
          electrical: "hsl(var(--subject-electrical))",
          mechatronics: "hsl(var(--subject-mechatronics))",
          building: "hsl(var(--subject-building))",
          automotive: "hsl(var(--subject-automotive))",
          "wood-tech": "hsl(var(--subject-wood-tech))",
          "metal-tech": "hsl(var(--subject-metal-tech))",
          marine: "hsl(var(--subject-marine))",
          aviation: "hsl(var(--subject-aviation))",
          economics: "hsl(var(--subject-economics))",
          sociology: "hsl(var(--subject-sociology))",
          psychology: "hsl(var(--subject-psychology))",
          citizenship: "hsl(var(--subject-citizenship))",
          "visual-arts": "hsl(var(--subject-visual-arts))",
          "performing-arts": "hsl(var(--subject-performing-arts))",
          theatre: "hsl(var(--subject-theatre))",
          "sports-science": "hsl(var(--subject-sports-science))",
          "power-mech": "hsl(var(--subject-power-mech))",
          "drawing-design": "hsl(var(--subject-drawing-design))",
          religious: "hsl(var(--subject-religious))",
          "language-activities": "hsl(var(--subject-language-activities))",
          psychomotor: "hsl(var(--subject-psychomotor))",
          sensory: "hsl(var(--subject-sensory))",
          "number-work": "hsl(var(--subject-number-work))",
          outdoor: "hsl(var(--subject-outdoor))",
          "listening-speaking": "hsl(var(--subject-listening-speaking))",
          "pre-reading": "hsl(var(--subject-pre-reading))",
          "pre-writing": "hsl(var(--subject-pre-writing))",
          storytelling: "hsl(var(--subject-storytelling))",
          counting: "hsl(var(--subject-counting))",
          shapes: "hsl(var(--subject-shapes))",
          "sorting-patterns": "hsl(var(--subject-sorting-patterns))",
          measurement: "hsl(var(--subject-measurement))",
          "family-community": "hsl(var(--subject-family-community))",
          "plants-animals": "hsl(var(--subject-plants-animals))",
          "weather-safety": "hsl(var(--subject-weather-safety))",
          "drawing-painting": "hsl(var(--subject-drawing-painting))",
          modeling: "hsl(var(--subject-modeling))",
          "music-movement": "hsl(var(--subject-music-movement))",
          "dance-drama": "hsl(var(--subject-dance-drama))",
          "moral-values": "hsl(var(--subject-moral-values))",
          "character-dev": "hsl(var(--subject-character-dev))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
