// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_FUNCTIONS_URL = import.meta.env.VITE_SUPABASE_FUNCTIONS_URL;

const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// If the env vars are missing, export a lightweight fallback so the app still
// renders instead of crashing on startup. API calls will fail gracefully.
const createFallbackSupabase = () =>
  ({
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      signInWithOtp: async () => ({
        data: { user: null, session: null },
        error: new Error("Missing Supabase configuration."),
      }),
      verifyOtp: async () => ({
        data: { user: null, session: null },
        error: new Error("Missing Supabase configuration."),
      }),
      updateUser: async () => ({
        data: { user: null },
        error: new Error("Missing Supabase configuration."),
      }),
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: new Error("Missing Supabase configuration."),
      }),
      signUp: async () => ({
        data: { user: null, session: null },
        error: new Error("Missing Supabase configuration."),
      }),
      signOut: async () => ({ error: null }),
      admin: {
        deleteUser: async () => ({
          data: null,
          error: new Error("Missing Supabase configuration."),
        }),
      },
    },
    from: () => createQueryFallback(),
    storage: {
      from: () => ({
        upload: async () => ({
          data: null,
          error: new Error("Missing Supabase configuration."),
        }),
        remove: async () => ({
          data: null,
          error: new Error("Missing Supabase configuration."),
        }),
        getPublicUrl: () => ({ data: { publicUrl: "" } }),
        download: async () => ({
          data: null,
          error: new Error("Missing Supabase configuration."),
        }),
      }),
    },
    channel: () => createChannelFallback(),
    removeChannel: async () => null,
  }) as any;

const createQueryFallback = () =>
  new Proxy(
    {},
    {
      get: (_target, prop) => {
        if (prop === "then") return undefined;
        if (prop === "catch" || prop === "finally") return undefined;
        if (prop === "select" || prop === "insert" || prop === "update" || prop === "upsert" || prop === "delete" || prop === "eq" || prop === "order" || prop === "limit" || prop === "range" || prop === "neq" || prop === "gt" || prop === "gte" || prop === "lt" || prop === "lte" || prop === "ilike" || prop === "in" || prop === "contains" || prop === "overlaps" || prop === "textSearch" || prop === "match") {
          return () => createQueryFallback();
        }

        if (prop === "single") {
          return async () => ({
            data: null,
            error: new Error("Missing Supabase configuration."),
          });
        }

        if (prop === "maybeSingle") {
          return async () => ({
            data: null,
            error: new Error("Missing Supabase configuration."),
          });
        }

        if (prop === "then") {
          return undefined;
        }

        return () => createQueryFallback();
      },
    }
  ) as any;

const createChannelFallback = () =>
  new Proxy(
    {},
    {
      get: (_target, prop) => {
        if (prop === "then") return undefined;
        if (prop === "subscribe") return () => createChannelFallback();
        if (prop === "on") return () => createChannelFallback();
        if (prop === "unsubscribe") return async () => ({ error: null });
        return () => createChannelFallback();
      },
    }
  ) as any;

export const supabase = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
      ...(SUPABASE_FUNCTIONS_URL
        ? {
            functions: {
              url: SUPABASE_FUNCTIONS_URL,
            },
          }
        : {}),
    })
  : createFallbackSupabase();
